name: Sandbox integrity checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run whitelist check for default-feature provided ops
      run: cargo test --lib -- test::check_op_whitelist --exact --show-output  
